"""Add host_confirmed field to Lunch model

Revision ID: 33dfdada14bc
Revises: f17dd80cd9f3
Create Date: 2025-12-09 15:30:13.176289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dfdada14bc'
down_revision = 'f17dd80cd9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunches', schema=None) as batch_op:
        batch_op.drop_column('host_confirmed')

    # ### end Alembic commands ###
