"""Add queue_position to Member for manual hosting order override

Revision ID: 6e0c4ecf11f5
Revises: 8dfd46cc045b
Create Date: 2025-12-08 20:16:41.085698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0c4ecf11f5'
down_revision = '8dfd46cc045b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('queue_position')

    # ### end Alembic commands ###
