"""Add magic link auth fields to Member

Revision ID: 890c668561e4
Revises: 3bacd6fd35da
Create Date: 2025-12-06 23:58:34.185542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890c668561e4'
down_revision = '3bacd6fd35da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magic_link_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('magic_link_expires', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_members_magic_link_token', ['magic_link_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_members_magic_link_token', type_='unique')
        batch_op.drop_column('magic_link_expires')
        batch_op.drop_column('magic_link_token')

    # ### end Alembic commands ###
