"""Add member profile fields

Revision ID: 8dfd46cc045b
Revises: 890c668561e4
Create Date: 2025-12-07 14:38:16.780043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfd46cc045b'
down_revision = '890c668561e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('profile_public')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('website')
        batch_op.drop_column('business')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
