"""Add rate_limits table for magic link throttling

Revision ID: f17dd80cd9f3
Revises: 6e0c4ecf11f5
Create Date: 2025-12-09 14:56:08.619252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17dd80cd9f3'
down_revision = '6e0c4ecf11f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limits_key'), ['key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limits_key'))
        batch_op.drop_index(batch_op.f('ix_rate_limits_action'))

    op.drop_table('rate_limits')
    # ### end Alembic commands ###
